version: "3.8"
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: Uvali
      POSTGRES_PASSWORD: Uvali
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5434:5434

  api:
    build:
      context: ./Uvali.API
    depends_on:
      - db
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - 5000

  front:
    build:
      context: ./front
    depends_on:
      - api
    restart: always
    volumes:
      - ./front/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8082

  admin:
    build:
      context: ./admin
    depends_on:
      - front
    restart: always
    volumes:
      - ./admin/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084

  balancer:
    image: nginx:alpine
    depends_on:
      - admin
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
